name: halte
dependencies:
  - python=3.7.*
  - numpy
  - matplotlib=3.1.1
  - opencv=3.4.2
  - pandas=0.24.2
  - pillow=6.1.0
  - pydot=1.4.1
  - pyyaml>=5.1
  - scikit-learn=0.22
  - tensorflow>=2.0
  - tqdm=4.32.1
