# Project config #
project_name: 'test-custom-worker'
log_level: INFO


# Worker config #
worker:
  image: halte:latest

  volumes:
    /c/users/vbfal/projects/halte-data:
      bind: /data
      mode: rw
